webtalk_init -webtalk_dir E:/Academic/HDL/Image_Filter_myrepo/Image_FIlter/Image_FIlter.sim/sim_1/behav/xsim/xsim.dir/control_unit_test_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jul 24 20:33:05 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "15a3bc3c-ff83-454d-9436-ae46e665db23" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "aaf18c36767f412c9f6fa4765755fdd2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "22" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 2600X Six-Core Processor           " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3600 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "10852_KB" -context "xsim\\usage"
webtalk_transmit -clientid 773406951 -regid "" -xml E:/Academic/HDL/Image_Filter_myrepo/Image_FIlter/Image_FIlter.sim/sim_1/behav/xsim/xsim.dir/control_unit_test_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/Academic/HDL/Image_Filter_myrepo/Image_FIlter/Image_FIlter.sim/sim_1/behav/xsim/xsim.dir/control_unit_test_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/Academic/HDL/Image_Filter_myrepo/Image_FIlter/Image_FIlter.sim/sim_1/behav/xsim/xsim.dir/control_unit_test_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
