# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/padded_image_ram/padded_image_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==padded_image_ram || ORIG_REF_NAME==padded_image_ram} -quiet] -quiet

# IP: ip/input_output_ram/input_output_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==input_output_ram || ORIG_REF_NAME==input_output_ram} -quiet] -quiet

# XDC: ip/padded_image_ram/padded_image_ram_ooc.xdc

# XDC: ip/input_output_ram/input_output_ram_ooc.xdc
