# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
set_param synth.incrementalSynthesisCache C:/Users/User/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-11376-DESKTOP-V5A9UPS/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/Academic/HDL/Image_Filter_myrepo/Image_FIlter/Image_FIlter.cache/wt [current_project]
set_property parent.project_path E:/Academic/HDL/Image_Filter_myrepo/Image_FIlter/Image_FIlter.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo e:/Academic/HDL/Image_Filter_myrepo/Image_FIlter/Image_FIlter.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/Academic/HDL/Image_Filter_myrepo/Image_FIlter/Image_FIlter.srcs/sources_1/imports/Image_FIlter/image_ram_init_data.coe
add_files E:/Academic/HDL/Image_Filter_myrepo/Image_FIlter/Image_FIlter.srcs/sources_1/ip/padded_image_ram/imgsave.coe
add_files E:/Academic/HDL/Image_Filter_myrepo/Image_FIlter/Image_FIlter.srcs/sources_1/ip/padded_image_ram/padded_data.coe
read_vhdl -library xil_defaultlib {
  E:/Academic/HDL/Image_Filter_myrepo/Image_FIlter/Image_FIlter.srcs/sources_1/new/Convolve.vhd
  E:/Academic/HDL/Image_Filter_myrepo/Image_FIlter/Image_FIlter.srcs/sources_1/new/control_unit.vhd
  E:/Academic/HDL/Image_Filter_myrepo/Image_FIlter/Image_FIlter.srcs/sources_1/new/padding_unit.vhd
  E:/Academic/HDL/Image_Filter_myrepo/Image_FIlter/Image_FIlter.srcs/sources_1/new/ram_input_mux.vhd
  E:/Academic/HDL/Image_Filter_myrepo/Image_FIlter/Image_FIlter.srcs/sources_1/new/uart_comm_unit.vhd
  E:/Academic/HDL/Image_Filter_myrepo/Image_FIlter/Image_FIlter.srcs/sources_1/new/image_filter.vhd
}
read_ip -quiet E:/Academic/HDL/Image_Filter_myrepo/Image_FIlter/Image_FIlter.srcs/sources_1/ip/axi_uartlite_unit/axi_uartlite_unit.xci
set_property used_in_implementation false [get_files -all e:/Academic/HDL/Image_Filter_myrepo/Image_FIlter/Image_FIlter.srcs/sources_1/ip/axi_uartlite_unit/axi_uartlite_unit_board.xdc]
set_property used_in_implementation false [get_files -all e:/Academic/HDL/Image_Filter_myrepo/Image_FIlter/Image_FIlter.srcs/sources_1/ip/axi_uartlite_unit/axi_uartlite_unit_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Academic/HDL/Image_Filter_myrepo/Image_FIlter/Image_FIlter.srcs/sources_1/ip/axi_uartlite_unit/axi_uartlite_unit.xdc]

read_ip -quiet E:/Academic/HDL/Image_Filter_myrepo/Image_FIlter/Image_FIlter.srcs/sources_1/ip/padded_image_ram/padded_image_ram.xci
set_property used_in_implementation false [get_files -all e:/Academic/HDL/Image_Filter_myrepo/Image_FIlter/Image_FIlter.srcs/sources_1/ip/padded_image_ram/padded_image_ram_ooc.xdc]

read_ip -quiet E:/Academic/HDL/Image_Filter_myrepo/Image_FIlter/Image_FIlter.srcs/sources_1/ip/input_output_ram/input_output_ram.xci
set_property used_in_implementation false [get_files -all e:/Academic/HDL/Image_Filter_myrepo/Image_FIlter/Image_FIlter.srcs/sources_1/ip/input_output_ram/input_output_ram_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top image_filter -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef image_filter.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file image_filter_utilization_synth.rpt -pb image_filter_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
